name: Regression Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  execution:
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.LT_USERNAME }}
      LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
      
    steps:
      - name: Set up Node Env
        uses: actions/checkout@v5
      - name: Execute Cypress
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=https://staging.ismojo.com/signup
          env: tags=@dev

      - name: Run Cypress on LambdaTest
        run: npx lambdatest-cypress run    

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Results-${{matrix.containers}}
          path: cypress/reports/   